# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Welcome
    url: /
    weight: 10
  - name: Education
    url: education/
    weight: 11
  - name: Skills
    url: /#skills
    weight: 12
  - name: Publications
    url: /#papers
    weight: 13
  - name: Conferences
    url: /#conferences
    weight: 20
  - name: Research Projects
    url: projects/
    weight: 30
  - name: Tutorials
    url: tutorials/
    weight: 40
